[package]
name = "pixel-art-generator"
version = "0.1.0"
edition = "2024"
authors = ["Aritra Biswas <aritrabb@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/aritrabiswas2004/pixel-art-generator"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
image = "0.25.10"
